from django.urls import path
from . import views
from .telegram_webhook import telegram_webhook_view
from .telegram_miniapp import (
    miniapp_menu_view,
    miniapp_form_view,
    miniapp_reference_view,
    miniapp_submit_view,
    miniapp_download_view,
)
from .max_webhook import max_webhook_view
from . import max_views

app_name = 'proposals'

urlpatterns = [
    path('telegram/webhook/', telegram_webhook_view),
    path('max/webhook/', max_webhook_view),
    path('max-app/', max_views.max_app_view, name='max_app'),
    path('max/auth/validate/', max_views.max_auth_validate_view, name='max_auth_validate'),
    path('max/api/reference/', max_views.max_reference_view, name='max_reference'),
    path('max/api/tkp/single/submit/', max_views.max_submit_single_tkp_view, name='max_submit_single_tkp'),
    path('max/api/tkp/complex/submit/', max_views.max_submit_complex_tkp_view, name='max_submit_complex_tkp'),
    path('max/api/requisites/parse/', max_views.max_requisites_parse_view, name='max_requisites_parse'),
    path('max/api/requisites/save/', max_views.max_requisites_save_view, name='max_requisites_save'),
    path('max/api/counterparties/', max_views.max_counterparties_view, name='max_counterparties'),
    path('max/api/counterparties/<int:pk>/', max_views.max_counterparty_detail_view, name='max_counterparty_detail'),
    path('max/api/tkps/', max_views.max_tkps_view, name='max_tkps'),
    path('max/api/contract/submit/', max_views.max_contract_submit_view, name='max_contract_submit'),
    path('max/api/download/<str:file_type>/', max_views.max_download_view, name='max_download'),
    path('tkp-app/', miniapp_menu_view),
    path('tkp-app/form/', miniapp_form_view),
    path('tkp-app/reference/', miniapp_reference_view),
    path('tkp-app/submit/', miniapp_submit_view),
    path('tkp-app/download/<str:token>/', miniapp_download_view),
    path('table/', views.table_view, name='table'),
    path('tkp/<int:pk>/card/', views.tkp_card_view, name='tkp_card'),
    path('kanban/', views.kanban_view, name='kanban'),
    path('kanban/card/<int:tkp_id>/', views.kanban_card_detail_view, name='kanban_card_detail'),
    path('kanban/card/<int:tkp_id>/notes/', views.kanban_save_notes_view, name='kanban_save_notes'),
    path('kanban/card/<int:tkp_id>/field/', views.kanban_card_field_save_view, name='kanban_card_field_save'),
    path('kanban/column/title/', views.kanban_column_title_view, name='kanban_column_title'),
    path('kanban/column/create/', views.kanban_column_create_view, name='kanban_column_create'),
    path('kanban/column/reorder/', views.kanban_column_reorder_view, name='kanban_column_reorder'),
    path('kanban/card/move/', views.kanban_card_move_view, name='kanban_card_move'),
    path('contracts/', views.contract_table_view, name='contract_table'),
    path('contract/<int:tkp_id>/', views.contract_form_view, name='contract_form'),
    path('contract/editor/', views.contract_editor_view, name='contract_editor'),
    path('contract/editor/save/', views.contract_save_from_editor_view, name='contract_save_from_editor'),
    path('contract/<int:contract_id>/card/', views.contract_card_view, name='contract_card'),
    path('contract/<int:contract_id>/download/<str:file_type>/', views.contract_download_file_view, name='contract_download'),
    path('tariffs/', views.tariffs_view, name='tariffs'),
    path('service-descriptions/', views.service_descriptions_view, name='service_descriptions'),
    path('ris-text/', views.ris_text_view, name='ris_text'),
    path('requisites/', views.requisites_add_view, name='requisites_add'),
    path('counterparties/', views.counterparties_view, name='counterparties'),
    path('counterparties/search/', views.counterparty_search_view, name='counterparty_search'),
    path('counterparty/<int:pk>/json/', views.counterparty_json_view, name='counterparty_json'),
    path('complex/', views.complex_form_view, name='complex_form'),
    path('complex/confirm/', views.complex_confirm_view, name='complex_confirm'),
    path('universal/', views.universal_form_view, name='universal_form'),
    path('universal/confirm/', views.universal_confirm_view, name='universal_confirm'),
    path('confirm/', views.confirm_view, name='confirm'),
    path('download-success/', views.download_success_view, name='download_success'),
    path('send-tkp-email/', views.send_tkp_pdf_email_view, name='send_tkp_email'),
    path('download/<str:file_type>/', views.download_file_view, name='download_file'),
    path('start/', views.start_view, name='start'),
    path('instruction/', views.instruction_view, name='instruction'),
    path('', views.form_view, name='form'),
]
