# Generated by Django 6.0.2 on 2026-02-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование услуги"
                    ),
                ),
                (
                    "template_file",
                    models.CharField(
                        help_text="Имя .docx файла в папке templates_docx/",
                        max_length=255,
                        verbose_name="Файл шаблона",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
                "ordering": ["order", "name"],
            },
        ),
    ]
