# Generated by Django 6.0.2 on 2026-02-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="unit",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Цена в шаблоне = единица_измерения × площадь",
                max_digits=15,
                verbose_name="Единица измерения",
            ),
        ),
    ]
