# Generated by Django 6.0.2 on 2026-02-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0002_service_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="TKPRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номер ТКП"
                    ),
                ),
                (
                    "client",
                    models.CharField(blank=True, max_length=255, verbose_name="Клиент"),
                ),
                ("service", models.CharField(max_length=255, verbose_name="Услуга")),
                (
                    "sum_total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Сумма"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
            ],
            options={
                "verbose_name": "Запись ТКП",
                "verbose_name_plural": "Записи ТКП",
                "ordering": ["-created_at"],
            },
        ),
    ]
