# Generated by Django 6.0.2 on 2026-02-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0003_tkprecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tkprecord",
            name="number",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Номер документа"
            ),
        ),
    ]
