# Generated by Django 6.0.2 on 2026-02-18 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0004_alter_tkprecord_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название региона"
                    ),
                ),
            ],
            options={
                "verbose_name": "Регион",
                "verbose_name_plural": "Регионы",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="service",
            name="unit",
        ),
        migrations.AddField(
            model_name="service",
            name="unit_type",
            field=models.CharField(
                choices=[("m2", "м²"), ("piece", "шт")],
                default="m2",
                max_length=10,
                verbose_name="Единица измерения",
            ),
        ),
        migrations.CreateModel(
            name="RegionServicePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Цена за единицу",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proposals.region",
                        verbose_name="Регион",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proposals.service",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цена по региону",
                "verbose_name_plural": "Цены по регионам",
                "unique_together": {("region", "service")},
            },
        ),
    ]
