# Generated by Django 6.0.2 on 2026-02-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0005_region_remove_service_unit_service_unit_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Описание услуги (подставляется в Комментарий в Комплексном ТКП)",
            ),
        ),
    ]
