# Generated by Django 5.1.6 on 2026-02-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0006_add_service_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Counterparty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Наименование"
                    ),
                ),
                (
                    "inn",
                    models.CharField(blank=True, max_length=12, verbose_name="ИНН"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Адрес")),
                (
                    "director",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Генеральный директор"
                    ),
                ),
                (
                    "ogrn",
                    models.CharField(blank=True, max_length=15, verbose_name="ОГРН"),
                ),
                (
                    "account",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Расчетный счет"
                    ),
                ),
                (
                    "bank",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Наименование банка"
                    ),
                ),
                ("bik", models.CharField(blank=True, max_length=9, verbose_name="БИК")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=64, verbose_name="Телефон"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
            ],
            options={
                "verbose_name": "Контрагент",
                "verbose_name_plural": "Контрагенты",
                "ordering": ["-created_at"],
            },
        ),
    ]
