# Generated by Django 5.1.6 on 2026-02-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0007_add_counterparty"),
    ]

    operations = [
        migrations.AddField(
            model_name="counterparty",
            name="email",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Эл. почта"
            ),
        ),
        migrations.AddField(
            model_name="counterparty",
            name="kor_account",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Корр. счет"
            ),
        ),
        migrations.AddField(
            model_name="counterparty",
            name="kpp",
            field=models.CharField(blank=True, max_length=9, verbose_name="КПП"),
        ),
        migrations.AddField(
            model_name="tkprecord",
            name="room",
            field=models.TextField(
                blank=True, verbose_name="Параметры объекта / помещение"
            ),
        ),
        migrations.AddField(
            model_name="tkprecord",
            name="s",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Площадь / количество"
            ),
        ),
        migrations.AddField(
            model_name="tkprecord",
            name="text",
            field=models.TextField(
                blank=True, verbose_name="Произвольный текст из ТКП"
            ),
        ),
    ]
