# Generated by Django 5.1.6 on 2026-02-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0008_counterparty_contract_fields_and_tkp_card"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата договора")),
                (
                    "number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номер договора"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
            ],
            options={
                "verbose_name": "Запись договора",
                "verbose_name_plural": "Записи договоров",
                "ordering": ["-created_at"],
            },
        ),
    ]
