# Generated by Django 5.1.6 on 2026-02-27 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0009_add_contract_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="tkprecord",
            name="counterparty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="proposals.counterparty",
                verbose_name="Контрагент (заказчик)",
            ),
        ),
    ]
