# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0010_tkp_record_counterparty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tkprecord",
            name="counterparty",
        ),
    ]
