# Generated by Django 5.1.6 on 2026-02-27 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0012_tkp_record_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractrecord",
            name="client",
            field=models.CharField(blank=True, max_length=500, verbose_name="Клиент"),
        ),
        migrations.AddField(
            model_name="contractrecord",
            name="counterparty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="proposals.counterparty",
                verbose_name="Контрагент",
            ),
        ),
        migrations.AddField(
            model_name="contractrecord",
            name="docx_file",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Файл DOCX"
            ),
        ),
        migrations.AddField(
            model_name="contractrecord",
            name="pdf_file",
            field=models.CharField(blank=True, max_length=255, verbose_name="Файл PDF"),
        ),
        migrations.AddField(
            model_name="contractrecord",
            name="service",
            field=models.CharField(blank=True, max_length=255, verbose_name="Услуга"),
        ),
        migrations.AddField(
            model_name="contractrecord",
            name="status",
            field=models.CharField(
                choices=[("draft", "Черновик"), ("final", "Итоговый")],
                default="final",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="contractrecord",
            name="sum_total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="Сумма"
            ),
        ),
        migrations.AddField(
            model_name="contractrecord",
            name="tkp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="proposals.tkprecord",
                verbose_name="ТКП",
            ),
        ),
    ]
