# Generated by Django 5.1.6 on 2026-02-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0013_contract_record_extended"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractrecord",
            name="contract_snapshot",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Снимок реквизитов"
            ),
        ),
    ]
