# Generated by Django 5.1.6 on 2026-03-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0014_contract_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="tkprecord",
            name="notes",
            field=models.TextField(
                blank=True, default="", verbose_name="Заметки по сделке"
            ),
        ),
    ]
