# Generated by Django 5.1.6 on 2026-03-02 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0015_tkp_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KanbanColumnCustom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kanban_custom_columns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользовательская колонка канбана",
                "verbose_name_plural": "Пользовательские колонки канбана",
                "ordering": ["user", "order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="KanbanCardField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название поля"),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[("text", "Текст"), ("number", "Число")],
                        default="text",
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                ("value", models.TextField(blank=True, verbose_name="Значение")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "tkp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kanban_custom_fields",
                        to="proposals.tkprecord",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kanban_card_fields",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Доп. поле карточки канбана",
                "verbose_name_plural": "Доп. поля карточек канбана",
                "ordering": ["order", "pk"],
                "unique_together": {("user", "tkp", "name")},
            },
        ),
        migrations.CreateModel(
            name="KanbanCardPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_key", models.CharField(max_length=64, verbose_name="Колонка")),
                (
                    "tkp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kanban_positions",
                        to="proposals.tkprecord",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kanban_card_positions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция карточки канбана",
                "verbose_name_plural": "Позиции карточек канбана",
                "unique_together": {("user", "tkp")},
            },
        ),
        migrations.CreateModel(
            name="KanbanColumnTitleOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "column_key",
                    models.CharField(max_length=50, verbose_name="Ключ колонки"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kanban_column_title_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Название колонки канбана",
                "verbose_name_plural": "Названия колонок канбана",
                "unique_together": {("user", "column_key")},
            },
        ),
    ]
