# Generated by Django 6.0.3 on 2026-03-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0018_add_created_by_to_tkp_and_contract"),
    ]

    operations = [
        migrations.AddField(
            model_name="tkprecord",
            name="rows_json",
            field=models.JSONField(
                blank=True,
                help_text="Список строк: service_name, comment, srok, unit, quantity, price_per_unit, total",
                null=True,
                verbose_name="Строки комплексного ТКП (позиции)",
            ),
        ),
    ]
