# Generated by Django 4.2.29 on 2026-03-14 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0019_add_tkp_rows_json"),
    ]

    operations = [
        migrations.CreateModel(
            name="TkpTelegramDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_user_id",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Telegram user id"
                    ),
                ),
                (
                    "telegram_chat_id",
                    models.CharField(max_length=64, verbose_name="Telegram chat id"),
                ),
                (
                    "is_internal",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="Внутренний заказчик"
                    ),
                ),
                (
                    "date",
                    models.DateField(blank=True, null=True, verbose_name="Дата ТКП"),
                ),
                (
                    "internal_client",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Внутренний клиент"
                    ),
                ),
                (
                    "internal_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Стоимость для внутреннего заказчика",
                    ),
                ),
                (
                    "client",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Наименование клиента"
                    ),
                ),
                (
                    "room",
                    models.TextField(
                        blank=True, verbose_name="Параметры объекта / помещение"
                    ),
                ),
                (
                    "s",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Площадь / количество"
                    ),
                ),
                (
                    "srok",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Срок разработки"
                    ),
                ),
                (
                    "text",
                    models.TextField(blank=True, verbose_name="Произвольный текст"),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Сырые значения"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="proposals.region",
                        verbose_name="Регион",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="proposals.service",
                        verbose_name="Услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Черновик ТКП (Telegram)",
                "verbose_name_plural": "Черновики ТКП (Telegram)",
                "ordering": ["-updated_at"],
            },
        ),
    ]
